-- MySQL Script generated by MySQL Workbench
-- vie 19 ago 2022 01:51:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `simm` ;

-- -----------------------------------------------------
-- Schema simm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simm` ;
USE `simm` ;

-- -----------------------------------------------------
-- Table `simm`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`empresas` (
  `idempresas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `logo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`idempresas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `role` VARCHAR(15) NULL DEFAULT 'user',
  `active` TINYINT(1) NULL DEFAULT '0',
  `photo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `empresas_idempresas` INT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_empresas_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_users_empresas`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`metod_costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`metod_costos` (
  `idmetod_costos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `interes` VARCHAR(100) NULL,
  `seguro` VARCHAR(100) NULL,
  `dep_maq` VARCHAR(100) NULL,
  `dep_neum` VARCHAR(100) NULL,
  `arreglos_maq` VARCHAR(100) NULL,
  `cons_comb` VARCHAR(100) NULL,
  `cons_lub` VARCHAR(100) NULL,
  `operador` VARCHAR(100) NULL,
  `mantenimiento` VARCHAR(150) NULL,
  `administracion` VARCHAR(150) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `users_idusers` INT NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  PRIMARY KEY (`idmetod_costos`),
  INDEX `fk_metod_costos_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_metod_costos_empresas_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_metod_costos_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_metod_costos_empresas`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`constantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`constantes` (
  `idconstantes` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `description` VARCHAR(200) NULL,
  `value` DECIMAL(10,5) NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `created` DATE NULL,
  `finished` VARCHAR(45) NULL,
  PRIMARY KEY (`idconstantes`),
  INDEX `fk_constantes_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_constantes_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_constantes_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_constantes_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`worksgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`worksgroups` (
  `idworksgroups` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `hash_id` VARCHAR(255) NOT NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idworksgroups`),
  INDEX `fk_worksgroups_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_worksgroups_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_worksgroups_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_worksgroups_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`destinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`destinos` (
  `iddestinos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `address` VARCHAR(150) NULL,
  `email` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `logo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`iddestinos`),
  INDEX `fk_destinos_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_destinos_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_destinos_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destinos_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(255) NULL,
  `orden` INT NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `users_idusers` INT NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_productos_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_productos_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`destinos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`destinos_productos` (
  `iddestinos_productos` INT NOT NULL AUTO_INCREMENT,
  `destinos_iddestinos` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  `precio` DECIMAL(10,5) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`iddestinos_productos`),
  INDEX `fk_destinos_productos_destinos1_idx` (`destinos_iddestinos` ASC) VISIBLE,
  INDEX `fk_destinos_productos_productos1_idx` (`productos_idproductos` ASC) VISIBLE,
  CONSTRAINT `fk_destinos_productos_destinos1`
    FOREIGN KEY (`destinos_iddestinos`)
    REFERENCES `simm`.`destinos` (`iddestinos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_destinos_productos_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `simm`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`maquinas` (
  `idmaquinas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `marca` VARCHAR(150) NULL,
  `propia` TINYINT(1) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `created` DATE NULL,
  `finished` DATE NULL,
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idmaquinas`),
  UNIQUE INDEX `idmaquinas_UNIQUE` (`idmaquinas` ASC) VISIBLE,
  INDEX `fk_maquinas_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_maquinas_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_maquinas_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maquinas_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`centros_costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`centros_costos` (
  `idcentros_costos` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `orden` VARCHAR(45) NOT NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idcentros_costos`),
  INDEX `fk_centros_costos_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_centros_costos_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_centros_costos_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_centros_costos_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`costos_maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`costos_maquinas` (
  `idcostos_maquinas` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `val_adq` FLOAT NULL,
  `val_neum` FLOAT NULL,
  `vida_util` FLOAT NULL,
  `vida_util_neum` FLOAT NULL,
  `horas_total_uso` FLOAT NULL,
  `horas_efec_uso` FLOAT NULL,
  `horas_mens_uso` FLOAT NULL,
  `horas_dia_uso` FLOAT NULL,
  `tasa_int_simple` FLOAT NULL,
  `factor_cor` FLOAT NULL,
  `coef_err_mec` FLOAT NULL,
  `consumo` FLOAT NULL,
  `lubricante` FLOAT NULL,
  `costo_alquiler` FLOAT NULL,
  `maquinas_idmaquinas` INT NOT NULL,
  `created` DATE NOT NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL,
  `users_idusers` INT NOT NULL,
  `worksgroups_idworksgroups` INT NOT NULL,
  `centros_costos_idcentros_costos` INT NOT NULL,
  `metod_costos_idmetod_costos` INT NOT NULL,
  PRIMARY KEY (`idcostos_maquinas`, `worksgroups_idworksgroups`),
  UNIQUE INDEX `idcostos_maquinas_UNIQUE` (`idcostos_maquinas` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_costos_maquinas_maquinas1_idx` (`maquinas_idmaquinas` ASC) VISIBLE,
  INDEX `fk_costos_maquinas_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_costos_maquinas_worksgroups1_idx` (`worksgroups_idworksgroups` ASC) VISIBLE,
  INDEX `fk_costos_maquinas_centros_costos1_idx` (`centros_costos_idcentros_costos` ASC) VISIBLE,
  INDEX `fk_costos_maquinas_metod_costos1_idx` (`metod_costos_idmetod_costos` ASC) VISIBLE,
  CONSTRAINT `fk_costos_maquinas_maquinas1`
    FOREIGN KEY (`maquinas_idmaquinas`)
    REFERENCES `simm`.`maquinas` (`idmaquinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costos_maquinas_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costos_maquinas_worksgroups1`
    FOREIGN KEY (`worksgroups_idworksgroups`)
    REFERENCES `simm`.`worksgroups` (`idworksgroups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costos_maquinas_centros_costos1`
    FOREIGN KEY (`centros_costos_idcentros_costos`)
    REFERENCES `simm`.`centros_costos` (`idcentros_costos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_costos_maquinas_metod_costos1`
    FOREIGN KEY (`metod_costos_idmetod_costos`)
    REFERENCES `simm`.`metod_costos` (`idmetod_costos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`operarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`operarios` (
  `idoperarios` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NOT NULL,
  `lastname` VARCHAR(100) NOT NULL,
  `dni` INT NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `logo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NULL DEFAULT '1',
  `users_idusers` INT NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  PRIMARY KEY (`idoperarios`),
  UNIQUE INDEX `idoperarios_UNIQUE` (`idoperarios` ASC) VISIBLE,
  INDEX `fk_operarios_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_operarios_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_operarios_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operarios_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`operarios_maquinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`operarios_maquinas` (
  `idoperarios_maquinas` INT NOT NULL AUTO_INCREMENT,
  `sueldo` DECIMAL(10,5) NULL,
  `operarios_idoperarios` INT NOT NULL,
  `maquinas_idmaquinas` INT NOT NULL,
  `created` DATE NOT NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idoperarios_maquinas`),
  INDEX `fk_operarios_maquinas_operarios1_idx` (`operarios_idoperarios` ASC) VISIBLE,
  INDEX `fk_operarios_maquinas_maquinas1_idx` (`maquinas_idmaquinas` ASC) VISIBLE,
  CONSTRAINT `fk_operarios_maquinas_operarios1`
    FOREIGN KEY (`operarios_idoperarios`)
    REFERENCES `simm`.`operarios` (`idoperarios`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_operarios_maquinas_maquinas1`
    FOREIGN KEY (`maquinas_idmaquinas`)
    REFERENCES `simm`.`maquinas` (`idmaquinas`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`lotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`lotes` (
  `idlotes` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `provincia` VARCHAR(50) NULL,
  `departamento` VARCHAR(100) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idlotes`),
  UNIQUE INDEX `idlotes_UNIQUE` (`idlotes` ASC) VISIBLE,
  INDEX `fk_lotes_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_lotes_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_lotes_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lotes_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`propietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`propietarios` (
  `idpropietarios` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(100) NULL,
  `lastname` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  `tipo` VARCHAR(50) NULL,
  `dni` VARCHAR(20) NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(50) NULL,
  `logo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  `users_idusers` INT NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  `phone` VARCHAR(50) NULL,
  PRIMARY KEY (`idpropietarios`),
  INDEX `fk_propietarios_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_propietarios_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_propietarios_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_propietarios_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`parcelas` (
  `idparcelas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `lotes_idlotes` INT NOT NULL,
  `propietarios_idpropietarios` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`idparcelas`),
  UNIQUE INDEX `idparcelas_UNIQUE` (`idparcelas` ASC) VISIBLE,
  INDEX `fk_parcelas_lotes1_idx` (`lotes_idlotes` ASC) VISIBLE,
  INDEX `fk_parcelas_propietarios1_idx` (`propietarios_idpropietarios` ASC) VISIBLE,
  INDEX `fk_parcelas_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_parcelas_lotes1`
    FOREIGN KEY (`lotes_idlotes`)
    REFERENCES `simm`.`lotes` (`idlotes`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcelas_propietarios1`
    FOREIGN KEY (`propietarios_idpropietarios`)
    REFERENCES `simm`.`propietarios` (`idpropietarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcelas_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`contratistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`contratistas` (
  `idcontratistas` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NULL,
  `email` VARCHAR(50) NULL,
  `phone` VARCHAR(50) NULL,
  `logo` VARCHAR(255) NULL,
  `folder` VARCHAR(255) NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  `active` VARCHAR(45) NOT NULL DEFAULT '1',
  `users_idusers` INT NOT NULL,
  PRIMARY KEY (`idcontratistas`),
  INDEX `fk_contratistas_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_contratistas_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`maq_cont_prod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`maq_cont_prod` (
  `id_maq_cont_prod` INT NOT NULL AUTO_INCREMENT,
  `contratistas_idcontratistas` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  `maquinas_idmaquinas` INT NOT NULL,
  `costo` DECIMAL(10,5) NOT NULL,
  `created` DATE NULL,
  `finished` DATE NULL,
  INDEX `fk_maq_cont_prod_contratistas1_idx` (`contratistas_idcontratistas` ASC) VISIBLE,
  INDEX `fk_maq_cont_prod_productos1_idx` (`productos_idproductos` ASC) VISIBLE,
  INDEX `fk_maq_cont_prod_maquinas1_idx` (`maquinas_idmaquinas` ASC) VISIBLE,
  PRIMARY KEY (`id_maq_cont_prod`),
  CONSTRAINT `fk_maq_cont_prod_contratistas1`
    FOREIGN KEY (`contratistas_idcontratistas`)
    REFERENCES `simm`.`contratistas` (`idcontratistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maq_cont_prod_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `simm`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_maq_cont_prod_maquinas1`
    FOREIGN KEY (`maquinas_idmaquinas`)
    REFERENCES `simm`.`maquinas` (`idmaquinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`lista_constantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`lista_constantes` (
  `idlista_constantes` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `users_idusers` INT NOT NULL,
  `empresas_idempresas` INT NOT NULL,
  PRIMARY KEY (`idlista_constantes`),
  INDEX `fk_lista_constantes_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_lista_constantes_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  CONSTRAINT `fk_lista_constantes_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lista_constantes_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simm`.`arreglos_mecanicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`arreglos_mecanicos` (
  `idarreglos_mecanicos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `num_comprobante` VARCHAR(100) NULL,
  `concepto` VARCHAR(255) NULL,
  `mano_obra` DECIMAL(10,5) NULL,
  `repuestos` DECIMAL(10,5) NULL,
  `total` DECIMAL(10,5) NULL DEFAULT ('mano_obra' + 'repuestos'),
  `worksgroups_idworksgroups` INT NOT NULL,
  `maquinas_idmaquinas` INT NOT NULL,
  `parcelas_idparcelas` INT NULL,
  `empresas_idempresas` INT NOT NULL,
  `users_idusers` INT NOT NULL,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `modified` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`idarreglos_mecanicos`),
  INDEX `fk_arreglos_mecanicos_worksgroups1_idx` (`worksgroups_idworksgroups` ASC) VISIBLE,
  INDEX `fk_arreglos_mecanicos_maquinas1_idx` (`maquinas_idmaquinas` ASC) VISIBLE,
  INDEX `fk_arreglos_mecanicos_parcelas1_idx` (`parcelas_idparcelas` ASC) VISIBLE,
  INDEX `fk_arreglos_mecanicos_empresas1_idx` (`empresas_idempresas` ASC) VISIBLE,
  INDEX `fk_arreglos_mecanicos_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_arreglos_mecanicos_worksgroups1`
    FOREIGN KEY (`worksgroups_idworksgroups`)
    REFERENCES `simm`.`worksgroups` (`idworksgroups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arreglos_mecanicos_maquinas1`
    FOREIGN KEY (`maquinas_idmaquinas`)
    REFERENCES `simm`.`maquinas` (`idmaquinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arreglos_mecanicos_parcelas1`
    FOREIGN KEY (`parcelas_idparcelas`)
    REFERENCES `simm`.`parcelas` (`idparcelas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arreglos_mecanicos_empresas1`
    FOREIGN KEY (`empresas_idempresas`)
    REFERENCES `simm`.`empresas` (`idempresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arreglos_mecanicos_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `simm`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `simm` ;

-- -----------------------------------------------------
-- Placeholder table for view `simm`.`lista_constantes_filter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`lista_constantes_filter` (`name` INT, `empresas_idempresas` INT);

-- -----------------------------------------------------
-- Placeholder table for view `simm`.`top_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`top_users` (`idusers` INT, `email` INT, `password` INT, `firstname` INT);

-- -----------------------------------------------------
-- Placeholder table for view `simm`.`arreglos_mecanicos_year`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simm`.`arreglos_mecanicos_year` (`idarreglos_mecanicos` INT, `fecha` INT, `num_comprobante` INT, `concepto` INT, `mano_obra` INT, `repuestos` INT, `total` INT, `worksgroups_idworksgroups` INT, `maquinas_idmaquinas` INT, `parcelas_idparcelas` INT, `empresas_idempresas` INT, `users_idusers` INT, `created` INT, `modified` INT);

-- -----------------------------------------------------
-- View `simm`.`lista_constantes_filter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simm`.`lista_constantes_filter`;
USE `simm`;
CREATE 

 OR REPLACE VIEW `simm`.`lista_constantes_filter` AS
    SELECT 
        `simm`.`lista_constantes`.`name` AS `name`,
        `simm`.`lista_constantes`.`empresas_idempresas` AS `empresas_idempresas`
    FROM
        `simm`.`lista_constantes`
    WHERE
        `simm`.`lista_constantes`.`name` IN (SELECT 
                `simm`.`constantes`.`name`
            FROM
                `simm`.`constantes`)
            IS FALSE;

-- -----------------------------------------------------
-- View `simm`.`top_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simm`.`top_users`;
USE `simm`;
CREATE 
 OR REPLACE VIEW `simm`.`top_users` AS
    SELECT 
        `simm`.`users`.`idusers` AS `idusers`,
        `simm`.`users`.`email` AS `email`,
        `simm`.`users`.`password` AS `password`,
        `simm`.`users`.`firstname` AS `firstname`
    FROM
        `simm`.`users`
    ORDER BY `simm`.`users`.`idusers`
    LIMIT 1;

-- -----------------------------------------------------
-- View `simm`.`arreglos_mecanicos_year`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simm`.`arreglos_mecanicos_year`;
USE `simm`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `simm`.`arreglos_mecanicos_year` AS
    SELECT 
        `simm`.`arreglos_mecanicos`.`idarreglos_mecanicos` AS `idarreglos_mecanicos`,
        `simm`.`arreglos_mecanicos`.`fecha` AS `fecha`,
        `simm`.`arreglos_mecanicos`.`num_comprobante` AS `num_comprobante`,
        `simm`.`arreglos_mecanicos`.`concepto` AS `concepto`,
        `simm`.`arreglos_mecanicos`.`mano_obra` AS `mano_obra`,
        `simm`.`arreglos_mecanicos`.`repuestos` AS `repuestos`,
        `simm`.`arreglos_mecanicos`.`total` AS `total`,
        `simm`.`arreglos_mecanicos`.`worksgroups_idworksgroups` AS `worksgroups_idworksgroups`,
        `simm`.`arreglos_mecanicos`.`maquinas_idmaquinas` AS `maquinas_idmaquinas`,
        `simm`.`arreglos_mecanicos`.`parcelas_idparcelas` AS `parcelas_idparcelas`,
        `simm`.`arreglos_mecanicos`.`empresas_idempresas` AS `empresas_idempresas`,
        `simm`.`arreglos_mecanicos`.`users_idusers` AS `users_idusers`,
        `simm`.`arreglos_mecanicos`.`created` AS `created`,
        `simm`.`arreglos_mecanicos`.`modified` AS `modified`
    FROM
        `simm`.`arreglos_mecanicos`
    WHERE
        (`simm`.`arreglos_mecanicos`.`fecha` >= (SELECT MAKEDATE(YEAR(NOW()), 1)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
